### ISSUE TITLE
NLE Migration - JUROR.MANUALS allows NULL DoB values

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#100]
### What is the issue?
in the JUROR.MANUALS table, the DOB field allows null, but in the modernised schema there is a not null constraint.

### What are the next actions?
Investigate if records exist in production with null values and decide whether to alter the schema/application to handle these values

**Comment by ChrisWCGI** [comment]
There are 815 rows in MANUALS with no DOB on the PROD database.
Only 75 of them have a DOB in the POOL table.

**Comment by CCHAPMAN01** [comment]
dropping not null constraint as part of migration
