### ISSUE TITLE
NLE Migration - JUROR.MANUALS has record with no history

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#101]
### What is the issue?
Unable to derive date created (which has a not null constraint in the new schema)

### What are the steps to replicate?
```
select * from juror.MANUALS m where not exists (select ph.part_no from juror.part_hist ph where ph.part_no = m.PART_NO)
```

### What are the next actions?
Investigate if similar records exist in production and decide how to sanitise the data prior to migration

**Comment by ChrisWCGI** [comment]
On the prod database ...

1 record with manuals.status = 'A' and no history
671 records with manuals.status = 'Q' and no history
265 records with manuals.status = 'R' and no history

I suggest using date_added as date_created when there is no history

**Comment by CCHAPMAN01** [comment]
Migration script updated to use date_added for the one case when status = 'A' and no history exists
