### ISSUE TITLE
NLE Migration - DEF_LETT has records with no corresponding history

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#105]
### What is the issue?
Expected count does not match actual count for DEF_LETT history updates - DEF_LETT records exists where no corresponding history items can be found

### What are the steps to replicate?
```
select  	dl.part_no,
			dl.date_def::date as other_information_date,
			dl.exc_code as other_information_reference,
			dl.date_printed,
			ph.history_code,
			ph.other_information 
from 		juror.def_lett dl
left join	juror.part_hist ph
	on		dl."owner" = ph."owner" 
			and dl.part_no = ph.part_no 
			and dl.date_printed::date = ph.date_part::date 
			and ph.history_code = 'RDEF'
where 	dl.date_printed is not null
		and dl."owner" != '400'
```

### What are the next actions?
Investigate if similar records exist in production and decide how to sanitise the data prior to migration

**Comment by ChrisWCGI** [comment]
No rows in the def_lett table on the prod database where there is no RDEF row in part_hist with date_part the same date as date_printed.
