### ISSUE TITLE
NLE Migration - EXC_LETT has records with no corresponding history

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#107]
### What is the issue?
Expected count does not match actual count for EXC_LETT history updates - EXC_LETT records exist where no corresponding history items can be found

### What are the steps to replicate?
```
select  el.part_no,
		el.date_excused::date as other_information_date,
		el.exc_code as other_information_reference,
		el.date_printed,
		ph.history_code,
		ph.other_information
from 	juror.exc_lett el
left join	juror.part_hist ph
	on		ph."owner" = el."owner" 
			and ph.part_no = el.part_no 
			and ph.date_part::date = el.date_printed::date
			and ph.history_code = 'REXC'
where 	el.date_printed is not null
		and el."owner" != '400'
```

### What are the next actions?
Investigate if similar records exist in production and decide how to sanitise the data prior to migration

**Comment by ChrisWCGI** [comment]
No rows in the exc_lett table on the prod database where there is no REXC row in part_hist with date_part the same date as date_printed.
