### ISSUE TITLE
NLE Migration - AUDIT_F_REPORT inconsistent with APPEARANCES (LOC_CODE)

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#109]
### What is the issue?
LOC_CODE doesn't necessarily match the LOC_CODE in APPEARANCES

### What are the steps to replicate?
```
select owner, part_no, faudit, loc_code from juror.audit_f_report
except
select owner, part_no, faudit, loc_code from juror.appearances
```

### What are the next actions?
Investigate if similar records exist in production and decide how to sanitise the data prior to migration

**Comment by ChrisWCGI** [comment]
Running the query in prod returns at least (stopped the execution). Further prod data analysis needed.

**Comment by CCHAPMAN01** [comment]
migration script always uses loc_code from appearances
