### ISSUE TITLE
PROD - JUROR - Investigate performance issue with bureau_transfer_date

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#147]
After migrating jurors in 0016a - the script which tries to set the new bureau_transfer_date property (0016b) is taking an excessive amount of time (yet to get it to complete at all!)

Investigate whether the script can be refactored to improve performance.

**Comment by ChrisWCGI** [comment]
Craig to amend the bureau_snap_shot script to also set the bureau transfer date based on the bureau data.

**Comment by CCHAPMAN01** [comment]
Liam has confirmed with Janet that where no bureau transfer date exists in the Oracle DB (records prior to 2022) then do not calculate a value - migrate as null (same as source)
