### ISSUE TITLE
CTC Migration - PRINT_FILES duplicate records

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#55]
### What would you like to change?
JUROR.PRINT_FILES has duplicate records in CTC

![image](https://github.com/hmcts/juror-database-migration/assets/62246193/9ca96e87-513e-4f4f-b2c8-8e6a199eb7e9)

Should we sanitise the data and de-duplicate records in this table prior to migration? Or introduce a new column to act as a key?

### How do you think that would improve the project?

ora2pg requires a primary key for data validation so introducing a unique constraint is essential for governance

### If this entry is related to a bug, please provide the steps to reproduce it

```
select
	count(1) as duplicate_count,
	PRINTFILE_NAME,
	CREATION_DATE,
	FORM_TYPE,
	DETAIL_REC,
	EXTRACTED_FLAG,
	PART_NO,
	DIGITAL_COMMS	
from
	JUROR.PRINT_FILES
group by
	PRINTFILE_NAME,
	CREATION_DATE,
	FORM_TYPE,
	DETAIL_REC,
	EXTRACTED_FLAG,
	PART_NO,
	DIGITAL_COMMS
having 
	count(1) > 1;
```

**Comment by ChrisWCGI** [comment]
There are no duplicate rows in print_files on the prod database. The combination of printfile_name, creation date and part_no is unique.
