### ISSUE TITLE
CTC Migration - FORM_ATTR missing columns

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#57]
### What would you like to change?
In CTC there are 2 additional columns in the FORM_ATTR table:
- PART_NO_OFFSET
- CHECK_FOR_DECEASED

### How do you think that would improve the project?
Are these columns in live/ Do we need to migrate them using the ora2pg tool?

<img width="1318" alt="image" src="https://github.com/hmcts/juror-database-migration/assets/62246193/e46bcef9-4318-4ae6-899b-f39b339abf62">

**Comment by ChrisWCGI** [comment]
PART_NO_OFFSET and CHECK_FOR_DECEASED do not exist in FORM_ATTR on the prod database.
