### ISSUE TITLE
CTC Migration - EXPORT_PLACEHOLDERS duplicate records

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#63]
### What would you like to change?
Are there duplicate records in production? Are we happy with de-duplicating them?

### How do you think that would improve the project?
Sanitise the data, de-duplicate redundant copies of data

### If this entry is related to a bug, please provide the steps to reproduce it
![image](https://github.com/hmcts/juror-database-migration/assets/62246193/1915956e-f3fe-4e72-8a58-c6ed38ea614d)

**Comment by ChrisWCGI** [comment]
There are no duplicate records in EXPORT_PLACEHOLDERS on the prod database.
