### ISSUE TITLE
CTC Migration - UNIQUE_POOL multiple rows with READ_ONLY = 'N'

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#65]
### What would you like to change?
Sanitise the data so only one row per pool number has the READ_ONLY value set to 'N'

### How do you think that would improve the project?
Allows migration scripts to identify the currently active for for a given pool number to de-duplicate records

### If this entry is related to a bug, please provide the steps to reproduce it
`select owner, pool_no, read_only  from juror.unique_pool where pool_no = '415240401'`

![image](https://github.com/hmcts/juror-database-migration/assets/62246193/7417cf6e-e71f-4f52-9618-c0f7f5ffdbe0)

**Comment by ChrisWCGI** [comment]
There are no pool numbers on the prod database that have read_only = 'N' on both the Bureau and the Court copy of the pool
