### ISSUE TITLE
CTC Migration - UNIQUE_POOL court copy status is transferred but no Bureau copy exists

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#66]
### What would you like to change?
Sanitise data so UNIQUE_POOL records with a NEW_REQUEST status of 'T' and READ_ONLY value of 'Y' must have a Bureau owned copy where READ_ONLY = 'N'

### How do you think that would improve the project?
If no Bureau copy exists, then revert the NEW_REQUEST value to 'Y' and READ_ONLY to 'N'

### If this entry is related to a bug, please provide the steps to reproduce it
```
select
	*
from
	juror.unique_pool up
where
	exists (
	select
		count(1),
		p.pool_no
	from
		juror.unique_pool p
	where
		p.pool_no = up.pool_no
	group by
		p.pool_no
	having
		(count(1) = 1))
	and read_only = 'Y'
```

**Comment by ChrisWCGI** [comment]
There are 1,266 pool numbers on the prod database that a court owner row in unique_pool with new_request = 'T' but no bureau owned row. The court owned records all have read_only = 'Y'.

This likely where the bureau have deleted a pool that is no longer needed.

**Comment by CCHAPMAN01** [comment]
Migration script updated
new step added to migrate pools with only inactive records
