### ISSUE TITLE
CTC Migration - POOL single records with READ_ONLY = 'Y'

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#68]
### What would you like to change?
Sanitise the data so if there is only one copy of a juror record, the READ_ONLY value is 'N'

### How do you think that would improve the project?
Allow data migration to correctly migrate the correct version of each record

### If this entry is related to a bug, please provide the steps to reproduce it
```
select		"owner", part_no, read_only, is_active, status
from		juror.pool p
where exists (
select 		count(1), jp.part_no, jp.read_only, jp.is_active, jp.status
from		juror.pool jp
where 		jp.part_no = p.part_no
group by	jp.part_no, jp.read_only, jp.is_active, jp.status
having 		count(1) = 1)
			and p.read_only = 'Y';
```

**Comment by ChrisWCGI** [comment]
Running the SQL from 'steps to reproduce it' on the prod database returns 1.4 million rows owned by the bureau with status 2 and is_active = Y, 484,000 rows owned by the bureau with status 1 and is_active = Y plus circa 3,000 other rows.

Looks like all the bureau records are returned by that SQL which suggests to me that the SQL is not right.

I checked one juror returned by the SQL and that was owned by the bureau and it rows owned by the court with read_only = N i.e. it wasn't a juror that only had rows with read_only = Y.

**Comment by ChrisWCGI** [comment]
The following query counts the number of jurors in the juror.pool table that do not have any records with read_only = 'N'.

select p.owner, p.read_only, p.is_active, p.status, count(1)
from pool p
where p.part_no in (
   select jp.part_no
   from pool jp
   group by jp.part_no
   having sum(decode(jp.read_only,'N',1,0)) = 0)
group by owner, read_only, is_active, status

Running the query on the prod database gives the following counts ....

1,615 jurors that are bureau owned with status 1, is_Active = Y and only have read_only = 'Y'
29 jurors that are bureau owned with is_active = Y and only have read_only = 'Y'
   27 of these have status 2,6 or 7
   2 of these have status 3 or 4 (yes, really - bureau owned records with status 3 or 4)
10 jurors that are bureau owned and only have read_only null
    8 of these have is_active = Y and status 5 or 6
    2 of these have is_active = N and status 7 or 8
12 jurors that are court owned with is_active = Y and status 2 and only have read_only = 'Y'
  3 jurors that are court owned and only have read_only null
