### ISSUE TITLE
CTC Migration - JUROR_RESPONSE has records missing from POOL

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#69]
### What would you like to change?
Sanitise data so orphaned records do not exist prior to migration

### How do you think that would improve the project?
Allow data migration to complete successfully and enforce new database key constraints

### If this entry is related to a bug, please provide the steps to reproduce it
```
select juror_number from juror_digital.juror_response
except
select part_no from juror.pool;
```

Need to identify records in the JUROR_DIGITAL schema related to the response and sanitise those as well, e.g. JUROR_RESPONSE_AUD

**Comment by ChrisWCGI** [comment]
There are no rows in the juror_digital response table on the prod database where the juror_number does not exist in the pool table.

There is however 1 juror, 347062375, where there is only 1 row in the pool table and that row has is_active = 'N' with status = 8 and owner = '400'
