### ISSUE TITLE
CTC Migration - PRINT_FILES has orphaned records (no corresponding juror in POOL)

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#73]
### What would you like to change?
Sanistise data to remove bulk print data where no corresponding juror can be found

### How do you think that would improve the project?
Allow for accurate migration of data to comply with the new schema designs and constraints

### If this entry is related to a bug, please provide the steps to reproduce it
select part_no from print_files pf 
except
select part_no from pool;

![image](https://github.com/hmcts/juror-database-migration/assets/62246193/5281ba58-30bf-42bd-b0a3-a5aca82b2715)

**Comment by ChrisWCGI** [comment]
There are 123 rows in print_files on the prod database with a part_no that does not have a row in the pool table.
There is 1 row in print_files on the prod database that does not have a part_no. The part_no will be somewhere in the detail_rec and and that could be used to set the part_no column under an incident.
