### ISSUE TITLE
CTC Migration - TRIAL records with invalid courtrooms

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#75]
### What would you like to change?
Validate TRIAL records have a valid ROOM_NO value (courtroom exists in migrated data)

### How do you think that would improve the project?
Allow for accurate migration and prevent data loss

### If this entry is related to a bug, please provide the steps to reproduce it
```
select
	distinct tl.trial_no,
	tl."owner"
from
	trial_lookup tl
left join juror_mod.courtroom c on
	tl.room_no = c.room_number
	and tl.loc_code = c.loc_code
where
	c.id is null
	and tl.loc_code is not null
```

**Comment by ChrisWCGI** [comment]
All the owner, room_no combinations in the trial table on the prod database exist in the location table
