### ISSUE TITLE
CTC Migration - PART_EXPENSES has orphaned records

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#86]
### What would you like to change?
Validate there are no orphaned records in production where expense records exist without a corresponding appearances record

### How do you think that would improve the project?
Allow for accurate data migration and reconciliation

### If this entry is related to a bug, please provide the steps to reproduce it
select OWNER, part_no, att_date from juror.PART_EXPENSES pe
minus
select OWNER, part_no, att_date from juror.APPEARANCES a;

![image](https://github.com/hmcts/juror-database-migration/assets/62246193/af80e601-b523-4679-9f25-f4bb9c954e99)

**Comment by ChrisWCGI** [comment]
Only 1 of the 41 orphaned rows in part_expenses on the PROD database has a row in audit_report (app_stage=9).
All 41 rows just have number_atts = 1  in part_expenses i.e. expenses  have not been paid.

**Comment by CCHAPMAN01** [comment]
archive orphaned records in migration schema (log table)
