### ISSUE TITLE
NLE Migration - UNIQUE_POOL has invalid records

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#95]
### What is the issue?
6 records exist in NLE where there is only a single copy of the UNIQUE_POOL record - but that record has read_only = 'Y' suggesting it is inactive

### What are the steps to replicate?
```
select 		pool_no, 
			count(1) as no_pool_requests,
			sum(case when read_only = 'N' then 1 else 0 end) as active_count
			
from		juror.unique_pool
group by	pool_no
having		count(1) >= 1 
			and sum(case when read_only = 'N' then 1 else 0 end) = 0;
```

### What are the next actions?
Investigate if similar records exist in production and decide whether we need to migrate them or not

**Comment by ChrisWCGI** [comment]
Running the sql from 'steps to replicate' on the prod database returns the following ...

1,539 pools owned by the Bureau with a max(return)date) of 22/05/20217.
... these might be pools that were transferred from the bureau but then deleted by the courts

1,282 pools owned by the Courts with a max(return_date) of 22/07/2024.
... these might be pools that were requested by the courts but deleted by the bureau and hence not transferred back to the courts

893 of the pools have no jurors in them i.e. most pools have jurors in them.
1,185 of the pools with jurors have at least 1 juror with is_active = 'Y'.
744 of the pools only have jurors with is_active = 'N'.
