### ISSUE TITLE
NLE Migration - JUROR_DIGITAL.STAFF_JUROR_RESPONSE_AUDIT has orphaned records

### ISSUE THREAD

**Issue by CCHAPMAN01** [hmcts/juror-database-migration#99]
### What is the issue?
Over 300 records exist in NLE where the JUROR_NUMBER in the STAFF_JUROR_RESPONSE_AUDIT table does not have a corresponding record in the JUROR_RESPONSE table

### What are the steps to replicate?
```
select count(1) from (
select lpad(juror_number, 9, '0') from STAFF_JUROR_RESPONSE_AUDIT sjra 
minus
select juror_number from JUROR_RESPONSE jr )
```

### What are the next actions?
Investigate if similar records exist in production and decide how to sanitise the data prior to migration

**Comment by ChrisWCGI** [comment]
There are no rows in STAFF_JUROR_RESPONSE_AUDIT on the PROD database that have a juror number that does not exist in JUROR_RESPONSE. Not an issue.

The PROD database did have 2 records in STAFF_JUROR_RESPONSE_AUDIT that have a juror number that does not appear in JUROR_RESPONSE but I have deleted them under an incident. They were both from 2018 and would have been deleted by Juror Digital Housekeeping if the juror number existed in JUROR_RESPONSE.
